version: "2.1"
 
services:
  nginx:
    image: nginx:latest
    container_name: p55-nginx
    depends_on:
      - actix-web-test
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 0.0.0.0:80:80
 #   network_mode: host
    restart: unless-stopped
    networks: 
      - p55_network
 #     - default

  actix-web-test:
    image: rustwebserver-actix-web-test:latest
    container_name: actix-web-test
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    ports:
      - "9101:9101"
    user: user
#    network_mode: host
    networks: 
      - p55_network
#       - default
    restart: unless-stopped
 
networks:
  p55_network:
    external: false